ex_compile: ex_compile.c
	gcc -o ex_compile ex_compile.c -I/usr/local/include/glib-2.0 -I/usr/local/lib/x86_64-linux-gnu/glib-2.0/include -lglib-2.0 && ./word_count


word_count: word_count.c
	gcc -o word_count word_count.c -I/usr/local/include/glib-2.0 -I/usr/local/lib/x86_64-linux-gnu/glib-2.0/include -lglib-2.0 && ./word_count
